version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:18.19.0
    working_directory: ~/repo

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      #- run:
      #    name: Install dpkg and fakeroot
      #    command: |
      #      sudo apt-get update -y
      #      sudo apt-get install -y dpkg fakeroot
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Generate Builds
          command: yarn build
      - run:
          name: Generate Tests
          command: npx jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
      - store_test_results:
          path: ./reports/
#  dist:
#    executor: node
#    steps:
#      - run:
#          name: Generate Artifacts
#          command: yarn dist
#      - run:
#          name: Copy Artifacts
#          command: |
#            mkdir -p /tmp/artifacts
#            cp dist/*.AppImage dist/*.flatpak dist/*.tar.gz /tmp/artifacts/
#      - store_artifacts:
#          path: /tmp/artifacts

workflows:
  build-test-dist:
    jobs:
      - build
      - test:
          requires:
            - build
